---
- name: Download backup file from remote server to local machine
  hosts: all
  become: true
  vars:
    remote_backup_file: /etc/myapp/config.txt.bak       # remote file path
    local_backup_dir: ./backups/                        # local folder to store backup

  tasks:
    - name: Ensure local backup directory exists
      local_action:
        module: file
        path: "{{ local_backup_dir }}"
        state: directory
        mode: '0755'

    - name: Fetch backup file from remote server
      fetch:
        src: "{{ remote_backup_file }}"
        dest: "{{ local_backup_dir }}"
        flat: yes   # keeps the original filename without creating host folders

    - name: Show message after backup
      debug:
        msg: "Backup of {{ remote_backup_file }} downloaded to {{ local_backup_dir }}"