---
- name: Create user with password and SSH key
  hosts: all
  become: true

  vars:
    username: ramesh
    user_password: "{{ '1234' | password_hash('sha256') }}"

  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Create .ssh directory
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Add SSH public key
      copy:
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        content: "{{ lookup('file', '/home/sudip/.ssh/id_ed25519.pub') }}"
        mode: '0600'
        owner: "{{ username }}"
        group: "{{ username }}"

