---
- name: Enable firewall ports for Nginx
  hosts: all
  become: true

  tasks:
    - name: Open HTTP port 80
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes

    - name: Open HTTPS port 443
      firewalld:
        port: 443/tcp
        permanent: true
        state: enabled
        immediate: yes

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
