---
- name: Start a service on remote server
  hosts: all
  become: true

  vars:
    service_name: nginx 
  tasks:
    - name: Start the service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes